//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestEasy_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public int AccountNo { get; set; }
        public int GuestID { get; set; }
        public float AmtDue { get; set; }
        public string CardNo { get; set; }
        public string CardName { get; set; }
        public int ExpMonth { get; set; }
        public int ExpYear { get; set; }
    
        public virtual Guest Guest { get; set; }
    }
}
